controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

velocity_controller:
  ros__parameters:
    joints:
      - back_left_wheel_hinge
      - back_right_wheel_hinge
      - left_wheel_hinge
      - right_wheel_hinge
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity